<div class="container-fluid text-center users">
    <div class="row user-head-row d-none d-md-flex" id="user-head-row">
        <div class="col-md-2 th">
            JMÉNO
        </div>
        <div class="col-md-2 th">
            PŘÍJMENÍ
        </div>
        <div class="col-md-2 th">
            ULICE A ČÍSLO
        </div>
        <div class="col-md-2 th">
            MĚSTO
        </div>
        <div class="col-md-2 th">
            PSČ
        </div>
        <div class="col-md-2 th">
            AKCE
        </div>
    </div>
    <?php foreach ($persons as $person) : ?>
        <div class="row user-row mt-md-0 mt-2">


            <div class="d-md-none col-6 th">
                <strong class="align-middle">JMÉNO:</strong>
            </div>
            <div class="col-6 col-md-2 td">

                <?= $person["first_name"] ?>

            </div>

            <div class="d-md-none col-6 th">
                <strong class="">PŘÍJMENÍ:</strong>
            </div>
            <div class="col-6 col-md-2 td">

                <?= $person["last_name"] ?>

            </div>

            <div class="d-md-none col-6 th">
                <strong class="">ULICE A ČÍSLO:</strong>
            </div>
            <div class="col-6 col-md-2 td">

                <?= $person["street_and_number"] ?>

            </div>

            <div class="d-md-none col-6 th">
                <strong class="">MĚSTO:</strong>
            </div>
            <div class="col-6 col-md-2 td">

                <?= $person["city"] ?>

            </div>

            <div class="d-md-none col-6 th">
                <strong class="">PSČ:</strong>
            </div>
            <div class="col-6 col-md-2 td">

                <?= $person["ZIP"] ?>

            </div>



            <div class="d-md-none col-6 th">
                <strong class="">AKCE:</strong>
            </div>
            <div class="col-6 col-md-2 td action">
                <a href="profile/<?= $person["persons_id"] ?>">Detail</a>
                <a href="register/update/<?= $person["persons_id"] ?>"><img class="icon" src="img/pen.png" alt="editovat"></a>
                <a href="register/delete/<?= $person["persons_id"] ?>" onClick="return confirm('Jste si jistý, že chcete odstranit uživatele<?=$person["first_name"]?> <?=$person["last_name"]?>')"><img class="icon" src="img/cross.png" alt="odstranit"></a>
            </div>

        </div>
    <?php endforeach; ?>

    <nav aria-label="stránkování">
        <ul class="pagination justify-content-center ">
            <?php foreach ($pages as $page) : ?>
                <li class="page-item <?= $page["class"] ?>">
                    <a href="<?= $page["url"] ?>" class="page-link" tabindex="<?= $page["tabindex"] ?>">
                        <?= $page["label"] ?>
                    </a>
                </li>

            <?php endforeach; ?>
        </ul>
    </nav>
    
    <a href="register" class="btn btn-outline-light m-3 w-25 align-self add-button">Přidat klienta</a>
</div>
<script src="../scripts/sort.js"></script>
<script src="../scripts/check.js"></script>
