<h1>Seznam článků</h1>

<?php foreach ($articles as $article) : ?>
    <article>
        <header>
            <h2><a href="article/<?= $article['url'] ?>"><?= $article['title'] ?></a></h2>
            <em class="author"> autor: <?= $article["author" ]?> </em>
            <em class="date"> <?= $article["date"] ?> </em>         
        </header>
        <section>
            <?= $article['description'] ?>
        </section>
        <footer>
            <?php if ($admin) : ?>
                <a href="editor/<?= $article['url'] ?>">Editovat</a>
                <a href="article/<?= $article['url'] ?>/delete">Odstranit</a>
            <?php endif ?>
        </footer>
    </article>
<?php endforeach ?>
