<h1>Kontaktní formulář</h1>

<p>Kontaktujte nás odesláním formuláře níže.</p>

<form method="post" id="form-email">
    Vaše emailová adresa<br />
    <input type="email" name="email" required="required" value="<?= (isset($_POST['email'])) ? htmlspecialchars($_POST['email']) : ""?>" /><br />
    Antispam - zadejte aktuální rok<br />
    <input type="text" name="year" required="required" /><br />
    <textarea name="message"><?= (isset($_POST['message'])) ? htmlspecialchars($_POST['message']) : ""?></textarea><br />
    <input type="submit" value="Odeslat" />
</form>