<!DOCTYPE html>
<html lang="cs-cz">

<head>
    <base href="/pojistovna" />
    <meta charset="UTF-8" />
    <title><?= $title ?></title>
    <meta name="description" content="<?= $description ?>" />
    <meta name="keywords" content="<?= $keyWords ?>" />
    <link rel="stylesheet" href="bootstrap/css/bootstrap-grid.css" type="text/css" />
    <link rel="stylesheet" href="bootstrap/css/bootstrap.css" type="text/css" />
    <link rel="stylesheet" href="bootstrap/css/bootstrap-reboot.css" type="text/css" />
    <link rel="stylesheet" href="bootstrap/css/bootstrap-utilities.css" type="text/css" />
    <link rel="stylesheet" href="style.css" type="text/css" />

</head>

<body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="pojisteni">Pojišťovna</a>
            <?php if (!$user) : ?>
                <!--když uživatel není příhlášen (místo pole obsahuje null)-->
                <div class="order-md-last ms-auto me-2 dropdown">
                    <button data-bs-toggle="dropdown" type="button" class="btn btn-dark" aria-expanded="false">
                        <span class="align-middle d-none d-md-inline me-1 fw-bold">Přihlásit se</span>
                        <img class="menu-icon" src="img/user.png" alt="">
                    </button>
                    <div class="dropdown-menu dropdown-menu-dark dropdown-menu-end p-3 text-right">
                        <form method="POST" action="login" novalidate="novalidate">
                            <div class="mb-1">
                                <label for="user_name" class="text-white form-label">uživatelské jméno:</label>
                                <input type="text" name="user_name" id="user_name" class="form-control">
                            </div>
                            <div class="mb-1">
                                <label for="password" class="text-white form-label">heslo:</label>
                                <input type="password" id="password" name="password" class="mb-2 form-control">
                            </div>
                            <button type="submit" class="btn btn-sm btn-primary">Přihlásit</button>
                        </form>
                    </div>
                </div>

            <?php else : ?>
                <div class="dropdown order-md-last ms-auto me-2">
                    <button data-bs-toggle="dropdown" type="button" class="btn btn-dark" aria-expanded="false">
                        <span class="align-middle d-none d-md-inline me-1"><?= $user["user_name"] ?></span>
                        <img class="menu-icon" src="img/user.png" alt="">
                    </button>
                    <ul class="text-center dropdown-menu dropdown-menu-dark dropdown-menu-end">
                        <li><a href="profile/<?= $user["persons_id"] ?>" class="dropdown-item">profil</a></li>
                        <?php if ($user["admin"]) : ?>
                            <li><a href="admin" class="dropdown-item">administrace</a></li>
                        <?php endif; ?>
                        <li><a href="login/logout" class="dropdown-item">odhlásit</a></li>
                        </li>
                </div>
            <?php endif; ?>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navigation">
                <span class="navbar-toggler-icon"></span>
            </button>



            <div class="collapse navbar-collapse" id="navigation">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a href="" class="nav-link">link</a>
                    </li>
                    <li class="nav-item">
                        <a href="" class="nav-link">link</a>
                    </li>
                    <li class="nav-item">
                        <a href="" class="nav-link">link</a>
                    </li>


                </ul>
            </div>

        </div>

    </nav>
    
    <div class="messages" id ="messages">
        <!-- výpis zpráv -->
        <?php foreach ($messages as $message) : ?>
            <p class="<?= $message["type"]->name ?>" onClick = "closser(this);">
                <strong>
                    <?= $message["type"]->value ?>
                </strong>
                <?= $message["text"] ?>
            </p>
        <?php endforeach ?>
    </div>


    <main>
        
        <?php $this->controller->writeView(); ?>
    </main>

    <footer class="bg-dark p-2 text-white text-center">
        <p>
            Copyright © 2022 Martin Kikta
        </p>
    </footer>
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script> -->
    <script src="/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="../scripts/Closser.js"></script>
</body>

</html>

