<!DOCTYPE html>
<html lang="cs-cz">

<head>
    <base href="/pojistovna" />
    <meta charset="UTF-8" />
    <title><?= $title ?></title>
    <meta name="description" content="<?= $popis ?>" />
    <meta name="keywords" content="<?= $klicova_slova ?>" />
    <link rel="stylesheet" href="bootstrap/css/bootstrap-grid.css" type="text/css" />
    <link rel="stylesheet" href="bootstrap/css/bootstrap.css" type="text/css" />
    <link rel="stylesheet" href="bootstrap/css/bootstrap-reboot.css" type="text/css" />
    <link rel="stylesheet" href="style.css" type="text/css" />

</head>

<body>


    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="pojisteni">Pojištěnice</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a href="login/logout" class="ms-auto">Odhlásit</a>
            <div class="collapse navbar-collapse" id="navigation">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a href="article/uvod" class="nav-link">Úvod</a>
                    </li>
                    <li class="nav-item">
                        <a href="article" class="nav-link">Články</a>
                    </li>
                    <li class="nav-item">
                        <a href="contact" class="nav-link">Kontakt</a>
                    </li>
                    <li class="nav-item">
                    </li>
                </ul>
            </div>

        </div>

    </nav>


    <!-- výpis zpráv -->
    <?php foreach ($messages as $message) : ?>
        <p class="<?= $message["type"]->name ?>">
            <strong>
                <?= $message["type"]->value ?>
            </strong><?= $message["text"] ?>
        </p>
    <?php endforeach ?>

    <main>
        <?php $this->controller->writeView(); ?>
    </main>

    <footer>
        <p>Ukázkový tutoriál pro jednoduché MVC z programátorské sociální sítě
            <a href="http://www.itnetwork.cz" target="_blank">itnetwork.cz</a>.
        </p>
        <a href="admin">Administrace</a>
    </footer>
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script> -->
    <script src="/bootstrap/js/bootstrap.bundle.min.js"></script>
</body>

</html>