<div class="login-container container p-4 bg-dark rounded-5">
    <h2 class = "text-white mb-3 text-center">Přihlašte se</h2>
    <form method="POST" novalidate="novalidate" class="text-center">

        <div class="form-floating mb-3">
            <input type="text" name="user_name" id="user_name" autofocus class="form-control " value="<?=$_POST["user_name"]?>" placeholder="uživatelské jméno">
            <label for="user_name" class="form-label">uživatelské jméno:</label>
        </div>
        <div class="form-floating mb-3">
            <input type="password" id="password" name="password" class="form-control" placeholder="heslo:">
            <label for="password" class="form-label">heslo:</label>
        </div>
        <input type="submit" value="Přihlásit" class="btn btn-primary mb-3">
    </form>
    <p class="text-white text-left">
        Pokud ještě nemáte účet, <a href="register">zaregistrujte se</a>.
    </p>
</div>